feat: ТЗ 13
DariaChagadaeva/java-shareit pull request #1
Opened 2023-05-07 13:28 UTC by DariaChagadaeva

2023-05-08 13:43 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-05-08 13:43 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                              @RequestBody ItemDto itemDto) {
сюда добавьте @Valid

2023-05-08 13:43 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.isEmpty()) {
лучше в контроллере перед параметром поставьте @NotNUll

2023-05-08 13:43 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private User checkUserExists(Long userId) {
если вы называете метод check, то подразумевается что метод булевый. Или переименуйте например во что нибудь с get, или от этого и метода ниже можно избавиться

2023-05-08 13:43 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User checkUserExists(Long userId) {
смотрите коммент в itemServiceImpl

2023-05-10 17:28 UTC, DariaChagadaeva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private User checkUserExists(Long userId) {
Я как-то упустила про check. Спасибо большое, обязательно запомню! Переименовала метод

2023-05-10 17:28 UTC, DariaChagadaeva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User checkUserExists(Long userId) {
Переименовала метод

2023-05-10 17:29 UTC, DariaChagadaeva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                              @RequestBody ItemDto itemDto) {
Тут осознанно я не ставила валидацию, так как она важна при создании Item, но не должна учитываться при обновлении, так как при тестировании валидация противоречит некоторым условиям. Например при создании важно, чтобы все поля не были пустыми, какие-то не были null, но при обновлении те же самые поля могут быть пустыми.

2023-05-11 04:45 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-05-21 13:44 UTC, merged