feat: add bookings and comments
DariaChagadaeva/java-shareit pull request #2
Opened 2023-05-22 10:31 UTC by DariaChagadaeva

2023-05-23 10:25 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-05-23 10:25 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private BookingState parseState(String state) {
этот метод можно убрать в BookingState

2023-05-23 10:25 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequest.java
> +public class BookingRequest {
а здесь валидировать разве не надо?

2023-05-23 10:25 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
enum можно сравнивать через ==, вот так BookingStatus.APPROVED == booking.getStatus()

2023-05-23 11:06 UTC, DariaChagadaeva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
Спасибо, исправила!

2023-05-23 11:07 UTC, DariaChagadaeva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private BookingState parseState(String state) {
Перенесла

2023-05-23 11:10 UTC, DariaChagadaeva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequest.java
> +public class BookingRequest {
Опираясь на тз и тесты postman детальная проверка нужна на уровне сервиса, если в следующем ТЗ что-то изменится, я добавлю необходимое

2023-05-23 11:11 UTC, DariaChagadaeva commented
Эркин, добрый день! Внесла изменения

2023-05-24 08:50 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-06-01 19:55 UTC, merged