feat: add requests and tests
DariaChagadaeva/java-shareit pull request #3
Opened 2023-06-01 19:56 UTC by DariaChagadaeva

2023-06-03 11:04 UTC, ErkinKasymaliev requested changes
привет!
Хорошая работа!
Оставил один коммент

2023-06-03 11:04 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingForItem.java
> +    private Long id;
где то вы используете @FieldDefaults(level = AccessLevel.PRIVATE), а где то прописываете private. Давайте приведем к одному стилю

2023-06-03 12:54 UTC, DariaChagadaeva commented
Добрый день, Эркин! 
Спасибо! Буду внимательней! Всё исправила

2023-06-04 09:19 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-06-07 13:41 UTC, merged